apiVersion: v1
kind: Secret
metadata:
  name: lab-session-{{ .Values.session.id }}-secrets
  labels:
    app: lab-environment
    session-id: {{ .Values.session.id | quote }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  vscode-password: {{ .Values.codeServer.password | quote }}
