apiVersion: v1
kind: Service
metadata:
  name: lab-service-{{ .Values.session.id }}
  labels:
    app: lab-environment
    session-id: {{ .Values.session.id | quote }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    session-id: {{ .Values.session.id | quote }}
  type: {{ .Values.service.type }}
  ports:
  - name: vscode
    port: {{ .Values.service.ports.vscode }}
    targetPort: 8080
    protocol: TCP
  - name: terminal
    port: {{ .Values.service.ports.terminal }}
    targetPort: 8081
    protocol: TCP
  - name: vm-ssh
    port: {{ .Values.service.ports.ssh }}
    targetPort: 22
    protocol: TCP
